config/routes.rb
Leaflet::Application.routes.draw do
  resources :locations

  # You can have the root of your site routed with "root"
  root 'locations#drifter'
  delete 'purge' => 'locations#purge'
  post 'data' => 'locations#create'
  get 'simulation' =>"locations#simulation", :as => "simulation"

  #url redirects
  get "drifter" => 'locations#drifter', :as => "drifter"
  get "menu" => 'locations#menu', :as => "menu"
  get "history" => "locations#history", :as => "history"
  get "live" => "locations#live", :as => "live"
  get "point" => "locations#point"

end

app/models/location.rb
class Location < ActiveRecord::Base
	attr_accessible  :latitude, :longitude, :time, :valid_input, :gps_speed, :drifter_name, :sensor_data, :sensor_name

	def self.to_csv(options = {})
  		CSV.generate(options) do |csv|
    		csv << column_names
    		all.each do |loc|
      			csv << loc.attributes.values_at(*column_names)
    		end
  		end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper :all
  protect_from_forgery with: :exception

  before_filter :prepare_for_mobile

 private
  
  def mobile_device?
    if session[:mobile_param]
      session[:mobile_param] == "1"
    else
      request.user_agent =~ /Mobile|webOS/
    end
  end
  helper_method :mobile_device?

  def prepare_for_mobile
    session[:mobile_param] = params[:mobile] if params[:mobile]
    request.format = :mobile if mobile_device?
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  skip_before_filter  :verify_authenticity_token

  def purge
    Location.delete_all
    redirect_to locations_path()
  end


  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.find(:all,:order => "created_at DESC" )
    respond_to do |format|
      format.html
      format.csv { send_data @locations.to_csv }
      format.xls { send_data @locations.to_csv(col_sep: "\t") }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location =
      if params.has_key? :location
        Location.new(params[:location])
      elsif params.has_key? :drifter_name
        Location.new(params)
      else
        Location.new()
      end
    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :json => @location }
      else
        format.html { render action: 'new' }
        format.json { render :json => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  def drifter
    if params[:val].present?
      @id = params[:id]
      @l0 = Location.find_all_by_drifter_name("Drifter #"+@id.to_s)
    elsif params[:id].present?
      @id = params[:id]
      @specific = true
      @l = Location.find_all_by_drifter_name("Drifter #"+@id.to_s)
      @l0 = @l.last
    else
      @l0 = Location.all
    end
  end

  def simulation
    @l0 = Location.all
  end

  def menu
    p "in menu"
    if params.to_s.include? "checkbox"
      session[:drifter]=[]
      params.each {|key, value|
      if "#{key}".include? "checkbox"
        #p "#{key}".last(2).to_s
        session[:drifter].push "#{key}".last(1).to_i
      end }
    end
    p session[:drifter]
  end

  def history
    @l0 = Location.all
  end

  def live
    if params[:val].present?
      @id = params[:id]
      @l0 = Location.find_all_by_drifter_name("Drifter #"+@id.to_s)
    elsif params[:id].present?
      @id = params[:id]
      @specific = true
      @l = Location.find_all_by_drifter_name("Drifter #"+@id.to_s)
      @l0 = @l.last
    elsif params[:action] =="live"
      @l0 = Location.first
    else
      @l0 =Location.all
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
	def count_drift
		Location.count()
	end

	def first_long
		begin
			Location.first.longitude
		rescue
			false
		end
	end

	def first_lat
		begin
			Location.first.latitude
		rescue
			false
		end
	end

	def get_elms(nums)
		nums = 1 if nums == 0
		val = Location.where(drifter_name: "Drifter ##{nums}")
		val.order("created_at DESC").limit(5) if val
	end
end

app/views/layouts/_footer.html.erb
<nav id="footer" class="navbar navbar-default navbar-fixed-bottom" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle btn btn-primary" data-toggle="collapse" data-target="#footer-navbar">
          <span class="sr-only">Drifter searching options!</span>
        </button>
      </div>
      <!-- Collect the nav links for footer -->
      <div class="collapse navbar-collapse" id="footer-navbar">
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to image_tag("drifter.png"), drifter_path(:id => 1), class: "btn btn-inverse"%></li>
          <li><%= link_to "History", "/history", class: "btn btn-inverse" %></li>
          <li><%= link_to "Data", "/locations", class: "btn btn-inverse" %></li>
            <% if mobile_device? %>
          <li> <%= link_to "Full Site", root_path(:mobile => 0 ), :rel => "external",class: "btn btn-inverse" %></li>
            <% else %>
          <li><%= link_to "Mobile Site", params.merge(:mobile => 1 ),class: "btn btn-inverse"%></li>
            <% end %>
        </ul>
        <button type="button" class="navbar-toggle btn btn-primary" data-toggle="collapse" data-target="#footer-navbar">
           <span class="sr-only">Close this bar</span>
        </button>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_footer.mobile.erb
<!-- /footer -->
<div data-role="footer" data-theme="b" data-position="fixed">
  You are currently in <%= params[:action] %>
  <br>
  <%if params[:action] == "live" %>
    Select more here:<%= link_to "Back to menu", menu_path %>
  <% elsif params[:action] == "drifter" %>
	  <% if mobile_device? %>
	    <%= link_to "Full Site", root_path(:mobile => 0 ), :rel => "external",class: "btn btn-success" %>
	  <% else %>
	    <%= link_to "Mobile Site", params.merge(:mobile => 1 ),class: "btn btn-success"%>
	  <% end %>
  <% end %>
  <%= link_to_function "Back", "history.back()" unless params[:action] == "drifter"%> 
</div>

app/views/layouts/_header.html.erb
<nav id = "header" class="navbar navbar-default navbar-fixed-top" role="navigation">
   <div class="navbar-header">
      <br>
      <center>Water Drifter @Berkeley</center>      
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Leaflet Drifter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Basic Global javascript and css-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <!-- leaflet css and java script -->
    <%= stylesheet_link_tag href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" , media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js" , "data-turbolinks-track" => true %>
    <!-- fontmarker and integration to leaflet -->
    <%= stylesheet_link_tag href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css"  %>
    <link rel="stylesheet" href="dist/leaflet.awesome-markers.css">
    <script src="dist/leaflet.awesome-markers.js"></script>
    <!-- integrating google map and leaflet -->
    <%= javascript_include_tag "http://matchingnotes.com/javascripts/leaflet-google.js", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "http://maps.google.com/maps/api/js?v=3.2&sensor=false", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body id="<%= params[:controller]+"-"+params[:action] %>">
    <%= render partial: "/layouts/header" %>
    <%= yield %>
  </body>
  <%= render partial: "/layouts/footer" %>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mobile Drifter</title>
    <!-- gloabl css and js -->
    <%= stylesheet_link_tag "mobile" %>
    <%= javascript_include_tag "mobile"%>
    <!-- end globals -->
    <!--leaflet css & js -->
    <%= stylesheet_link_tag href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" , media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js" , "data-turbolinks-track" => true %>
    <!--leaflet fontawesome -->
    <%= stylesheet_link_tag href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" , media: "all", "data-turbolinks-track" => true %>
    <!-- leaflet fontawesome fusion -->
    <link rel="stylesheet" href="dist/leaflet.awesome-markers.css">
    <script src="dist/leaflet.awesome-markers.js"></script>
    <!-- integrating google map and leaflet -->
    <%= javascript_include_tag "http://matchingnotes.com/javascripts/leaflet-google.js", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "http://maps.google.com/maps/api/js?v=3.2&sensor=false", "data-turbolinks-track" => true %>
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
  </head>
  <body id="<%= params[:controller]+"-"+params[:action] %>">
    <%= yield %>
    <%= render partial: "/layouts/footer" %>
  </body>
</html>

app/views/locations/_map.html.erb
<script>
			<%= first_long = Location.first.longitude %>
			<%= first_lat = Location.first.latitude%>
			var map = new L.Map('map', {center: new L.LatLng(<%= first_lat%>-0.36093, <%= first_long%>+.26494), zoom: 16});
			//0.36093, -122.25803
      		var googleLayer = new L.Google('SATELLITE');
      		map.addLayer(googleLayer);
			 var adjust = L.AwesomeMarkers.icon({
			    icon: 'fa-adjust',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var asterisk = L.AwesomeMarkers.icon({
			    icon: 'fa-asterisk',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var down = L.AwesomeMarkers.icon({
			    icon: 'fa-hand-o-down',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var archive = L.AwesomeMarkers.icon({
			    icon: 'fa-archive',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var circle = L.AwesomeMarkers.icon({
			    icon: 'fa-circle',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var cloud = L.AwesomeMarkers.icon({
			    icon: 'fa-cloud',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var certificate = L.AwesomeMarkers.icon({
			    icon: 'fa-certificate',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var fighter_jet = L.AwesomeMarkers.icon({
			    icon: 'fa-fighter-jet',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var coffee = L.AwesomeMarkers.icon({
			    icon: 'fa-coffee',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var cog = L.AwesomeMarkers.icon({
			    icon: 'fa-cog',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var bug = L.AwesomeMarkers.icon({
			    icon: 'fa-bug',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var beer = L.AwesomeMarkers.icon({
			    icon: 'fa-beer',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var arrow = L.AwesomeMarkers.icon({
			    icon: 'fa-arrow-circle-o-right',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var dot = L.AwesomeMarkers.icon({
			    icon: 'fa-dot-circle-o',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var plus = L.AwesomeMarkers.icon({
			    icon: 'fa-plus-circle',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var rocket = L.AwesomeMarkers.icon({
			    icon: 'fa-rocket',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var smile = L.AwesomeMarkers.icon({
			    icon: 'fa-smile-o',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var star = L.AwesomeMarkers.icon({
			    icon: 'fa-star-o',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var shopping = L.AwesomeMarkers.icon({
			    icon: 'fa-shopping-cart',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var trophy = L.AwesomeMarkers.icon({
			    icon: 'fa-trophy',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			 var tachometer = L.AwesomeMarkers.icon({
			    icon: 'fa-tachometer',
			    prefix: 'fa',
			    markerColor:'orange'
			  });
			<% if @specific %>
				<% valid = @l0.valid_input.to_s %>
				<% name = @l0.drifter_name.to_s %>
				<% time = @l0.time.to_s %>
				<% speed = @l0.gps_speed %>
				  L.marker([ <%= @l0.latitude%> , <%= @l0.longitude%>], {icon: smile, riseOnHover:true}).addTo(map).bindPopup("<b>"+"<%= name %>"+", "+"<%= time %>"+". My current speed is "+"<%= speed %>"+"</b>").openPopup();
			<% else %>
				<% @l0.each do |location| %>
				<% valid = location.valid_input.to_s %>
				<% name = location.drifter_name.to_s %>
				<% time = location.time.to_s %>
				<% speed = location.gps_speed %>
				  L.marker([ <%= location.latitude%> , <%= location.longitude%>], {icon: smile, riseOnHover:true}).addTo(map).bindPopup("<b>"+"<%= name %>"+", "+"<%= time %>"+". My current speed is "+"<%= speed %>"+"</b>").openPopup();
				<% end%>
			<% end %>
			
			var popup = L.popup();
			function onMapClick(e) {
				popup
					.setLatLng(e.latlng)
					.setContent("You clicked the map at " + e.latlng.toString())
					.openOn(map);
			}
			map.on('click', onMapClick);
	</script>

app/views/locations/drifter.js.erb
$('#message_received').html("#{escape_javascript(render 'locations/drifterElm', data: @location, @specific)}");
console.log("#{escape_javascript(render 'locations/drifterElm', data: @location, @specific)}");
console.log("what is this");

app/views/locations/drifter.mobile.erb
<center>
    <h2> Please choose from the following drifters or select all, then click menu</h2>
</center>

<%= form_tag menu_path , :method => :get do %>
    <legend> Drifter Options:</legend>
        <input type="checkbox" name="checkbox-h-1" id="checkbox-h-6a">
        <label for="checkbox-h-6a">One</label>
        <input disabled="" type="checkbox" name="checkbox-h-2" id="checkbox-h-6b">
        <label for="checkbox-h-6b">Two</label>
        <input disabled="" type="checkbox" name="checkbox-h-3" id="checkbox-h-6c">
        <label for="checkbox-h-6c">Three</label>
        <input disabled="" type="checkbox" name="checkbox-h-3" id="checkbox-h-6d">
        <label for="checkbox-h-6d">Four</label>
        <input disabled="" type="checkbox" name="checkbox-h-4" id="checkbox-h-6e">
        <label for="checkbox-h-6e">Five</label>
        <input disabled="" type="checkbox" name="checkbox-h-5" id="checkbox-h-6f">
        <label for="checkbox-h-6f">Six</label>
        <input disabled="" type="checkbox" name="checkbox-h-6" id="checkbox-h-6g">
        <label for="checkbox-h-6g">Seven</label>
        <input disabled="" type="checkbox" name="checkbox-h-7" id="checkbox-h-6h">
        <label for="checkbox-h-6h">Eight</label>
        <input disabled="" type="checkbox" name="checkbox-h-8" id="checkbox-h-6i">
        <label for="checkbox-h-6i">Nine</label>
        <input disabled="" type="checkbox" name="checkbox-h-9" id="checkbox-h-6j">
        <label for="checkbox-h-6j">Ten</label>
        <input disabled="" type="checkbox" name="checkbox-h-10" id="checkbox-h-6k">
        <label for="checkbox-h-6k">Eleven</label>
        <input disabled="" type="checkbox" name="checkbox-h-11" id="checkbox-h-6l">
        <label for="checkbox-h-6l">Twelve</label>
        <input disabled="" type="checkbox" name="checkbox-h-12" id="checkbox-h-6m">
        <label for="checkbox-h-6m">Thirteen</label>
        <input disabled="" type="checkbox" name="checkbox-h-13" id="checkbox-h-6n">
        <label for="checkbox-h-6n">Fourteen</label>
        <input disabled="" type="checkbox" name="checkbox-h-14" id="checkbox-h-6o">
        <label for="checkbox-h-6o">Fiveteen</label>
        <input disabled="" type="checkbox" name="checkbox-h-15" id="checkbox-h-6p">
        <label for="checkbox-h-6p">Sixteen</label>
        <input disabled="" type="checkbox" name="checkbox-h-16" id="checkbox-h-6q">
        <label for="checkbox-h-6q">Seventeen</label>
        <input disabled="" type="checkbox" name="checkbox-h-17" id="checkbox-h-6r">
        <label for="checkbox-h-6r">Eighteen</label>
        <input disabled="" type="checkbox" name="checkbox-h-18" id="checkbox-h-6s">
        <label for="checkbox-h-6s">Nineteen</label>
        <input disabled="" type="checkbox" name="checkbox-h-19" id="checkbox-h-6t">
        <label for="checkbox-h-6t">Twenty</label>
        <input type="checkbox" name="checkbox-h-20" id="checkbox-h-6u">
        <label for="checkbox-h-6u">All</label>
        <br>
    <%= submit_tag "Go to Menu" %>
<% end %>

app/views/locations/edit.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/locations/index.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
  <h4><%= link_to "Purge Database", purge_path,
                                                :confirm => 'Pressing this will remove the whole database. Wish to continue?',
                                                :method => :delete,
                                                :class => 'btn btn-mini btn-danger' %>
</div>
<p>
  Download:
  <%= link_to "CSV", locations_path(format: "csv") %> |
  <%= link_to "Excel", locations_path(format: "xls") %>
</p>
<p>
  Elements recorded so far: <%= count_drift %>
</p>
<table class="table table-striped table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:drifter_name) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%= model_class.human_attribute_name(:gps_speed) %></th>
      <th><%= model_class.human_attribute_name(:sensor_name) %></th>
      <th><%= model_class.human_attribute_name(:sensor_data) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.id, location_path(location) %></td>
        <td><%= location.drifter_name %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.created_at.strftime('%b %d, %Y %l:%M:%S %p') %></td>
        <td><%= location.gps_speed %></td>
        <td><%= location.sensor_name %></td>
        <td><%= location.sensor_data %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_location_path(location), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      location_path(location),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/locations/index.mobile.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:latitude) %></th>
      <th><%= model_class.human_attribute_name(:longitude) %></th>
      <th><%= model_class.human_attribute_name(:time) %></th>
      <th><%= model_class.human_attribute_name(:valid_input) %></th>
      <th><%= model_class.human_attribute_name(:gps_speed) %></th>
      <th><%= model_class.human_attribute_name(:drifter_name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.id, location_path(location) %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.time %></td>
        <td><%= location.valid_input %></td>
        <td><%= location.gps_speed %></td>
        <td><%= location.drifter_name %></td>
        <td><%=l location.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_location_path(location), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      location_path(location),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_location_path,
            :class => 'btn btn-primary' %>

app/views/locations/menu.mobile.erb
<center><h1> Select mode! </h1></center>
<br>
<br>
 <center> Your current Drifter(s) is <%= session[:drifter] %></center>
<br>
<ul data-role="listview" data-inset="true" data-filter="true" data-input="#filter-for-listview">
    <li><%= link_to "Live", live_path,:rel => "external"%></li>
    <li><%= link_to "History", history_path , :rel => "external"%></li>
    <li><%= link_to "Data", locations_path %></li>
</ul>

app/views/locations/new.html.erb
<%- model_class = Location -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/locations/point.html.erb
<% if Location.any? %>
	<div id="map">	
	<script>
		var map = new L.Map('map', {center: new L.LatLng(<%= first_lat%>-0.36093, <%= first_long%>+.26494), zoom: 16});
		//0.36093, -122.25803
  		var googleLayer = new L.Google('SATELLITE');
  		map.addLayer(googleLayer);
  		var smile = L.AwesomeMarkers.icon({
		    icon: 'fa-smile-o',
		    prefix: 'fa',
		    markerColor:'orange'
		});
					console.log("this partical is called")
		$(document).ready(function () {
		    // will call refreshPartial every 3 seconds
		    setInterval(refreshPartial, 3000)

		});

		// calls action refreshing the partial
		function refreshPartial() {
			$.getJSON( "simulation", function( data ) {
		  		console.log(data);
		  		  $.each(data,function(key,value){
		  		  	console.log(value);
		  		  	console.log(value.time);
					L.marker([ value.latitude , value.longitude], {icon: smile, riseOnHover:true}).addTo(map).bindPopup("<b>"+value.drifter_name+", "+value.time+". My current speed is "+value.gps_speed+"</b>").openPopup();
					var popup = L.popup();
					function onMapClick(e) {
						popup
							.setLatLng(e.latlng)
							.setContent("You clicked the map at " + e.latlng.toString())
							.openOn(map);
					}
					map.on('click', onMapClick);
		  		  });
			});
		}
	</script>
	</div>
<% else %>
	Please wait for first data point to come in...
<% end %>

app/views/locations/show.mobile.erb
<h2>sup homies~</h2>

app/views/locations/test.mobile.erb
<link href="/assets/bootstrap_and_overrides.css?body=1" media="screen" rel="stylesheet" />
<h1><center>Hello this is mobile!</center></h1>
<center><p>
  <% if mobile_device? %>
    <%= link_to "Full Site", root_path(:mobile => 0 ), :rel => "external",class: "btn btn-success" %>
  <% else %>
    <%= link_to "Mobile Site", params.merge(:mobile => 1 ),class: "btn btn-success"%>
  <% end %>
</p>

<h2> Please choose from the following drifters or select all</h2>
<p>TODO: add the radio buttons here </p>
<p>1</P>
<p>20</p>
<p>all<p>
<%= link_to "Menu", menu_path, class: "btn btn-info"%></center>	